<?php

// DEFINIMOS UNA VARIABLE GLOBAL PARA TENER ACCESO A LA RUTA RAIZ DE MI PROYECTO
// DE ESTA MANERA SE FACILITA EL DIRECCIONAMIENTO EN LAS DISTINTAS PAGINAS.

define('RUTARAIZ','http://localhost/proyectos/portfoliomagazine');


?>